<a href="https://colab.research.google.com/github/DevNova11/EDA/blob/main/EXP4_28.07.2026/MissingValues2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imputation

In [3]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

new_df = pd.DataFrame(
    {
        "Score": [85, 92, np.nan, 78, 65, 90, np.nan, 88, 72, 80],
        "Hours_Studied": [5, np.nan, 7, 4, 3, 6, 8, np.nan, 3, 5],
        "Grade": ["A", "A", "B", "C", "D", "A", "B", "A", "C", np.nan],
    }
)

mean_imputer_new = SimpleImputer(strategy="mean")
new_df["Score_Mean"] = mean_imputer_new.fit_transform(new_df[["Score"]]).ravel()

median_imputer_new = SimpleImputer(strategy="median")
new_df["Hours_Studied_Median"] = median_imputer_new.fit_transform(
    new_df[["Hours_Studied"]]
).ravel()

mode_imputer_new = SimpleImputer(strategy="most_frequent")
new_df["Grade_Mode"] = mode_imputer_new.fit_transform(new_df[["Grade"]]).ravel()

num_cols_new = ["Score", "Hours_Studied"]
mice_imputer_new = IterativeImputer(max_iter=10, random_state=42)
df_mice_new = new_df[num_cols_new].copy()
df_mice_new.iloc[:, :] = mice_imputer_new.fit_transform(df_mice_new)
new_df["Score_MICE"] = df_mice_new["Score"]
new_df["Hours_Studied_MICE"] = df_mice_new["Hours_Studied"]

print(new_df)

   Score  Hours_Studied Grade  Score_Mean  Hours_Studied_Median Grade_Mode  \
0   85.0            5.0     A       85.00                   5.0          A
1   92.0            NaN     A       92.00                   5.0          A
2    NaN            7.0     B       81.25                   7.0          B
3   78.0            4.0     C       78.00                   4.0          C
4   65.0            3.0     D       65.00                   3.0          D
5   90.0            6.0     A       90.00                   6.0          A
6    NaN            8.0     B       81.25                   8.0          B
7   88.0            NaN     A       88.00                   5.0          A
8   72.0            3.0     C       72.00                   3.0          C
9   80.0            5.0   NaN       80.00                   5.0          A

   Score_MICE  Hours_Studied_MICE
0   85.000000            5.000000
1   92.000000            6.233521
2   97.068656            7.000000
3   78.000000            4.000000
4   65.000000            3.000000
5   90.000000            6.000000
6  104.064672            8.000000
7   88.000000            5.686666
8   72.000000            3.000000
9   80.000000            5.000000

# Missing Values

In [4]:
import numpy as np
import pandas as pd

# 1. Create a DataFrame with initial and added missing values
print("### 1. Creating DataFrame with missing values")
sales_data = np.random.randint(100, 1000, size=(5, 3))
sales_df = pd.DataFrame(sales_data,
                        index=['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
                        columns=['Region_A', 'Region_B', 'Region_C'])

sales_df['Region_D'] = np.nan # Entire column NaN initially
sales_df.loc['Tablet'] = np.random.randint(50, 500, size=4)
sales_df.loc['Speaker'] = np.nan # Entire row NaN
sales_df.loc['Mouse', 'Region_A'] = np.nan
sales_df.loc['Keyboard', 'Region_C'] = np.nan
sales_df.loc['Monitor', 'Region_D'] = 250.0 # Fill one NaN
display(sales_df)
print("\n")

# 2. Inspecting NaN values
print("### 2. Inspecting NaN values")
print("NaN count per column:")
display(sales_df.isnull().sum())
print("Total NaNs:", sales_df.isnull().sum().sum())
print("\n")

# 3. Dropping missing values
print("### 3. Dropping missing values")
print("Original:")
display(sales_df)
print("\nDrop rows with ANY NaN:")
display(sales_df.dropna())
print("\nDrop rows where ALL NaN:")
display(sales_df.dropna(how='all'))
print("\nDrop cols where ALL NaN:")
display(sales_df.dropna(how='all', axis=1))
print("\nDrop cols with < 5 non-NaNs:")
display(sales_df.dropna(thresh=5, axis=1))
print("\n")

# 4. Mathematical operations with NaN
print("### 4. Mathematical operations with NaN")
ar_sales = np.array([100, 200, np.nan, 300, 150])
ser_sales = pd.Series(ar_sales)
print(f"Series: {ser_sales.tolist()}")
print(f"Mean (ignores NaN): {ser_sales.mean()}")
print(f"Sum of 'Region_D': {sales_df['Region_D'].sum()}")
print(f"Cumsum of 'Region_A':\n{sales_df['Region_A'].cumsum().to_string()}")
print("\n")

# 5. Filling missing values
print("### 5. Filling missing values")
print("Original:")
display(sales_df)
print("\nFill NaN with 0:")
display(sales_df.fillna(0))
print("\nForward-fill 'Region_A':")
display(sales_df['Region_A'].fillna(method='ffill'))
print("\nBackward-fill 'Region_A':")
display(sales_df['Region_A'].fillna(method='bfill'))

### 1. Creating and populating DataFrame with missing values

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       NaN
Mouse          NaN     184.0     610.0       NaN
Keyboard     331.0     377.0       NaN       NaN
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       NaN
Tablet       408.0     198.0     358.0     280.0
Speaker        NaN       NaN       NaN       NaN

### 2. Inspecting NaN values
Count of NaN values per column:

Region_A    2
Region_B    1
Region_C    2
Region_D    5
dtype: int64

Total number of missing values: 10


### 3. Dropping missing values
Original DataFrame:

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       NaN
Mouse          NaN     184.0     610.0       NaN
Keyboard     331.0     377.0       NaN       NaN
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       NaN
Tablet       408.0     198.0     358.0     280.0
Speaker        NaN       NaN       NaN       NaN

Dropping rows with ANY NaN (df.dropna()):

         Region_A  Region_B  Region_C  Region_D
Monitor     319.0     997.0     728.0     250.0
Tablet      408.0     198.0     358.0     280.0

Dropping rows where ALL values are NaN (df.dropna(how='all')):

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       NaN
Mouse          NaN     184.0     610.0       NaN
Keyboard     331.0     377.0       NaN       NaN
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       NaN
Tablet       408.0     198.0     358.0     280.0

Dropping columns where ALL values are NaN (df.dropna(how='all', axis=1)):

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       NaN
Mouse          NaN     184.0     610.0       NaN
Keyboard     331.0     377.0       NaN       NaN
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       NaN
Tablet       408.0     198.0     358.0     280.0
Speaker        NaN       NaN       NaN       NaN

Dropping columns with less than 5 non-NaN values (df.dropna(thresh=5, axis=1)):

          Region_A  Region_B  Region_C
Laptop       599.0     488.0     635.0
Mouse          NaN     184.0     610.0
Keyboard     331.0     377.0       NaN
Monitor      319.0     997.0     728.0
Webcam       356.0     571.0     556.0
Tablet       408.0     198.0     358.0
Speaker        NaN       NaN       NaN

### 4. Mathematical operations with NaN
Series for math operations: [100.0, 200.0, nan, 300.0, 150.0]
Mean of series (ignores NaN by default): 187.5
Sum of 'Region_D' column: 530.0
Cumulative sum of 'Region_A' column:
Laptop       599.0
Mouse          NaN
Keyboard     930.0
Monitor     1249.0
Webcam      1605.0
Tablet      2013.0
Speaker        NaN


### 5. Filling missing values
Original DataFrame before filling NaN:

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       NaN
Mouse          NaN     184.0     610.0       NaN
Keyboard     331.0     377.0       NaN       NaN
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       NaN
Tablet       408.0     198.0     358.0     280.0
Speaker        NaN       NaN       NaN       NaN

Filling NaN values with 0 (df.fillna(0)):

          Region_A  Region_B  Region_C  Region_D
Laptop       599.0     488.0     635.0       0.0
Mouse          0.0     184.0     610.0       0.0
Keyboard     331.0     377.0       0.0       0.0
Monitor      319.0     997.0     728.0     250.0
Webcam       356.0     571.0     556.0       0.0
Tablet       408.0     198.0     358.0     280.0
Speaker        0.0       0.0       0.0       0.0

Forward-filling ('Region_A' column, method='ffill'):

/tmp/ipykernel_3506/4187794610.py:58: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(sales_df['Region_A'].fillna(method='ffill'))

Laptop      599.0
Mouse       599.0
Keyboard    331.0
Monitor     319.0
Webcam      356.0
Tablet      408.0
Speaker     408.0
Name: Region_A, dtype: float64

Backward-filling ('Region_A' column, method='bfill'):

/tmp/ipykernel_3506/4187794610.py:60: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(sales_df['Region_A'].fillna(method='bfill'))

Laptop      599.0
Mouse       331.0
Keyboard    331.0
Monitor     319.0
Webcam      356.0
Tablet      408.0
Speaker       NaN
Name: Region_A, dtype: float64