<a href="https://colab.research.google.com/github/DevNova11/EDA/blob/main/sportsdat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

df1Basketball = pd.DataFrame({'PlayerID': [1, 3, 5, 7, 9, 11, 21],
                              'PointsBasketball': [15, 22, 10, 30, 8, 18, 5]})
df2Basketball = pd.DataFrame({'PlayerID': [2, 4, 6, 8, 10, 12, 11, 23],
                              'PointsBasketball': [12, 25, 14, 28, 9, 20, 16, 7]})

df1Soccer = pd.DataFrame({'PlayerID': [1, 2, 13, 15, 17, 19, 21],
                           'GoalsSoccer': [2, 1, 3, 0, 2, 1, 0]})
df2Soccer = pd.DataFrame({'PlayerID': [14, 16, 18, 20, 19, 22, 24],
                           'GoalsSoccer': [1, 0, 2, 3, 1, 0, 1]})

print("Basketball Dataframe 1:")
display(df1Basketball)
print("\nBasketball Dataframe 2:")
display(df2Basketball)
print("\nSoccer Dataframe 1:")
display(df1Soccer)
print("\nSoccer Dataframe 2:")
display(df2Soccer)

Basketball Dataframe 1:

   PlayerID  PointsBasketball
0         1                15
1         3                22
2         5                10
3         7                30
4         9                 8
5        11                18
6        21                 5

Basketball Dataframe 2:

   PlayerID  PointsBasketball
0         2                12
1         4                25
2         6                14
3         8                28
4        10                 9
5        12                20
6        11                16
7        23                 7

Soccer Dataframe 1:

   PlayerID  GoalsSoccer
0         1            2
1         2            1
2        13            3
3        15            0
4        17            2
5        19            1
6        21            0

Soccer Dataframe 2:

   PlayerID  GoalsSoccer
0        14            1
1        16            0
2        18            2
3        20            3
4        19            1
5        22            0
6        24            1

### Combining Dataframes for Each Sport

First, we'll combine the individual dataframes for each sport into a single dataframe for Basketball and a single dataframe for Soccer, similar to how the `dfSE` and `dfML` were created in your example.

In [28]:
dfBasketball = pd.concat([df1Basketball, df2Basketball], ignore_index=True)
dfSoccer = pd.concat([df1Soccer, df2Soccer], ignore_index=True)

print("Combined Basketball Scores:")
display(dfBasketball)
print("\nCombined Soccer Scores:")
display(dfSoccer)

Combined Basketball Scores:

    PlayerID  PointsBasketball
0          1                15
1          3                22
2          5                10
3          7                30
4          9                 8
5         11                18
6         21                 5
7          2                12
8          4                25
9          6                14
10         8                28
11        10                 9
12        12                20
13        11                16
14        23                 7

Combined Soccer Scores:

    PlayerID  GoalsSoccer
0          1            2
1          2            1
2         13            3
3         15            0
4         17            2
5         19            1
6         21            0
7         14            1
8         16            0
9         18            2
10        20            3
11        19            1
12        22            0
13        24            1

### Option 1: Concatenating with `axis=1` (Side-by-Side Join - Often Not Ideal for Different IDs)

This method concatenates dataframes side-by-side. If the indices don't align perfectly (e.g., if PlayerIDs are not in the same order or counts are different), it can lead to `NaN` values and misaligned data. It's generally not recommended for joining based on a common identifier like `PlayerID` without careful index management.

In [29]:
df_concat_axis1 = pd.concat([dfBasketball, dfSoccer], axis=1)
display(df_concat_axis1)

    PlayerID  PointsBasketball  PlayerID  GoalsSoccer
0          1                15       1.0          2.0
1          3                22       2.0          1.0
2          5                10      13.0          3.0
3          7                30      15.0          0.0
4          9                 8      17.0          2.0
5         11                18      19.0          1.0
6         21                 5      21.0          0.0
7          2                12      14.0          1.0
8          4                25      16.0          0.0
9          6                14      18.0          2.0
10         8                28      20.0          3.0
11        10                 9      19.0          1.0
12        12                20      22.0          0.0
13        11                16      24.0          1.0
14        23                 7       NaN          NaN

### Option 2: Inner Merge (Players in Both Sports)

An inner merge (or inner join) will give us a dataframe containing only the players who appear in *both* the Basketball and Soccer dataframes. This means we get the list of multi-sport players.

In [30]:
df_inner_merge = dfBasketball.merge(dfSoccer, on='PlayerID', how='inner')
print("Players who played in both Basketball and Soccer (Inner Merge):")
display(df_inner_merge)

Players who played in both Basketball and Soccer (Inner Merge):

   PlayerID  PointsBasketball  GoalsSoccer
0         1                15            2
1        21                 5            0
2         2                12            1

### Option 3: Left Merge (All Basketball Players + Their Soccer Stats)

A left merge (or left join) will include all players from the 'left' dataframe (Basketball in this case) and their corresponding stats from the 'right' dataframe (Soccer). If a Basketball player did not play Soccer, their `GoalsSoccer` will be `NaN`.

In [31]:
df_left_merge = dfBasketball.merge(dfSoccer, on='PlayerID', how='left')
print("All Basketball Players and their Soccer Stats (Left Merge):")
display(df_left_merge)

All Basketball Players and their Soccer Stats (Left Merge):

    PlayerID  PointsBasketball  GoalsSoccer
0          1                15          2.0
1          3                22          NaN
2          5                10          NaN
3          7                30          NaN
4          9                 8          NaN
5         11                18          NaN
6         21                 5          0.0
7          2                12          1.0
8          4                25          NaN
9          6                14          NaN
10         8                28          NaN
11        10                 9          NaN
12        12                20          NaN
13        11                16          NaN
14        23                 7          NaN

### Option 4: Right Merge (All Soccer Players + Their Basketball Stats)

A right merge (or right join) is the opposite of a left merge. It includes all players from the 'right' dataframe (Soccer) and their corresponding stats from the 'left' dataframe (Basketball). If a Soccer player did not play Basketball, their `PointsBasketball` will be `NaN`.

In [32]:
df_right_merge = dfBasketball.merge(dfSoccer, on='PlayerID', how='right')
print("All Soccer Players and their Basketball Stats (Right Merge):")
display(df_right_merge)

All Soccer Players and their Basketball Stats (Right Merge):

    PlayerID  PointsBasketball  GoalsSoccer
0          1              15.0            2
1          2              12.0            1
2         13               NaN            3
3         15               NaN            0
4         17               NaN            2
5         19               NaN            1
6         21               5.0            0
7         14               NaN            1
8         16               NaN            0
9         18               NaN            2
10        20               NaN            3
11        19               NaN            1
12        22               NaN            0
13        24               NaN            1

### Answering the Head of Department's Questions (Sports Edition)

Now, let's answer questions about player participation, similar to your original problem statement.

In [33]:
df_all_players = pd.concat([dfBasketball[['PlayerID']], dfSoccer[['PlayerID']]]).drop_duplicates()
total_unique_players = df_all_players['PlayerID'].nunique()
print(f"Total unique players across both sports: {total_unique_players}")

Total unique players across both sports: 24

In [34]:
players_only_basketball = dfBasketball[~dfBasketball['PlayerID'].isin(dfSoccer['PlayerID'])]['PlayerID'].nunique()
print(f"Players who only appeared for Basketball: {players_only_basketball}")

Players who only appeared for Basketball: 11

In [35]:
players_only_soccer = dfSoccer[~dfSoccer['PlayerID'].isin(dfBasketball['PlayerID'])]['PlayerID'].nunique()
print(f"Players who only appeared for Soccer: {players_only_soccer}")

Players who only appeared for Soccer: 10

## Another Sports Scenario: Game Statistics

Let's consider a single dataset of general game statistics, similar to your `sales.csv` example. We can perform operations like adding new calculated columns, counting occurrences, and getting descriptive statistics.

In [36]:
game_stats_data = {
    'GameID': [101, 101, 102, 102, 103, 103, 104, 104, 105, 105],
    'PlayerID': [1, 2, 3, 4, 1, 5, 6, 7, 3, 8],
    'Team': ['Team A', 'Team B', 'Team A', 'Team B', 'Team A', 'Team B', 'Team A', 'Team B', 'Team A', 'Team B'],
    'FieldGoalsMade': [5, 7, 6, 8, 4, 9, 7, 5, 6, 8],
    'ThreePointersMade': [2, 1, 3, 2, 1, 2, 3, 1, 2, 0],
    'FreeThrowsMade': [3, 2, 4, 3, 2, 3, 1, 2, 4, 1],
    'Assists': [4, 3, 5, 2, 6, 4, 3, 5, 2, 4],
    'Rebounds': [8, 6, 7, 5, 9, 8, 6, 7, 5, 9]
}
game_stats_df = pd.DataFrame(game_stats_data)

print("Original Game Stats Dataframe:")
display(game_stats_df.head(10))

Original Game Stats Dataframe:

,GameID,PlayerID,Team,FieldGoalsMade,ThreePointersMade,FreeThrowsMade,Assists,Rebounds
0,101,1,Team A,5,2,3,4,8
1,101,2,Team B,7,1,2,3,6
2,102,3,Team A,6,3,4,5,7
3,102,4,Team B,8,2,3,2,5
4,103,1,Team A,4,1,2,6,9
5,103,5,Team B,9,2,3,4,8
6,104,6,Team A,7,3,1,3,6
7,104,7,Team B,5,1,2,5,7
8,105,3,Team A,6,2,4,2,5
9,105,8,Team B,8,0,1,4,9

In [37]:
game_stats_df['TotalPoints'] = (game_stats_df['FieldGoalsMade'] * 2) + \
                                (game_stats_df['ThreePointersMade'] * 3) + \
                                (game_stats_df['FreeThrowsMade'] * 1)

print("Game Stats Dataframe with TotalPoints:")
display(game_stats_df.head(10))

Game Stats Dataframe with TotalPoints:

,GameID,PlayerID,Team,FieldGoalsMade,ThreePointersMade,FreeThrowsMade,Assists,Rebounds,TotalPoints
0,101,1,Team A,5,2,3,4,8,19
1,101,2,Team B,7,1,2,3,6,19
2,102,3,Team A,6,3,4,5,7,25
3,102,4,Team B,8,2,3,2,5,25
4,103,1,Team A,4,1,2,6,9,13
5,103,5,Team B,9,2,3,4,8,27
6,104,6,Team A,7,3,1,3,6,24
7,104,7,Team B,5,1,2,5,7,15
8,105,3,Team A,6,2,4,2,5,22
9,105,8,Team B,8,0,1,4,9,17

In [38]:
print("Team counts:")
display(game_stats_df['Team'].value_counts())

Team counts:

Team
Team A    5
Team B    5
Name: count, dtype: int64

In [39]:
print("Descriptive statistics for Game Stats:")
display(game_stats_df.describe())

Descriptive statistics for Game Stats:

,GameID,PlayerID,FieldGoalsMade,ThreePointersMade,FreeThrowsMade,Assists,Rebounds,TotalPoints
count,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,103.000000,4.00000,6.500000,1.700000,2.500000,3.800000,7.000000,20.600000
std,1.490712,2.44949,1.581139,0.948683,1.080123,1.316561,1.490712,4.718757
min,101.000000,1.00000,4.000000,0.000000,1.000000,2.000000,5.000000,13.000000
25%,102.000000,2.25000,5.250000,1.000000,2.000000,3.000000,6.000000,17.500000
50%,103.000000,3.50000,6.500000,2.000000,2.500000,4.000000,7.000000,20.500000
75%,104.000000,5.75000,7.750000,2.000000,3.000000,4.750000,8.000000,24.750000
max,105.000000,8.00000,9.000000,3.000000,4.000000,6.000000,9.000000,27.000000